### ISSUE TITLE
Block producer

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-block-producer#1]
As a Koinos node cluster operator, I would like to produce new blocks.

- [x] Create application structure and main loop logic (#2)
- [x] Query transactions from the mempool (#3)
- [x] Borrow PoW logic from `block_producer_plugin` (#4)
- [x] Submit blocks to koinosd (#5)
