### ISSUE TITLE
Block Production Algorithm (Proof-of-Work)

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-block-producer#25]
As a Koinos blockchain tester, I would like a simple consensus algorithm to test the basics of the Koinos blockchain framework.

While not the desired long term consensus algorithm, PoW is quick and simple to implement as an initial consensus algorithm for early testing of Koinos.

- [x] Store the head block time in statedb and provide access to it via a system call `get_head_block_time` (koinos/koinos-chain#398)
- [x] We need to implement a PoW consensus algorithm in a smart contract and override the necessary system call (`verify_block_signature`). (koinos/koinos-system-contracts#4)
- [x] Extend the `block_producer` microservice to handle PoW production (#28)
- [x] Retrieve the current difficulty from the PoW smart contract (#30)
- [x] We need to dynamically check if the difficulty has been met in the block producer microservice (#31)
- [x] We need to listen for new blocks and restart the nonce discovery process (#32)
- [x] Perform some manual tests (integration) (#33)
